// Generated by protoc-gen-js-mjs
// Source: pokeworld/user/cs_user.proto

// Package: pokeworld.user.cs

// Enum: MessageId
export const MessageId = {
    INVALID: 0,
    REGISTER_REQUEST: 1001,
    REGISTER_RESPONSE: 1002,
    LOGIN_REQUEST: 1003,
    LOGIN_RESPONSE: 1004,
    ENTER_SERVER_REQUEST: 1005,
    ENTER_SERVER_RESPONSE: 1006,
    GET_SERVERS_REQUEST: 1007,
    GET_SERVERS_RESPONSE: 1008,
    GET_CREATED_PLAYERS_REQUEST: 1009,
    GET_CREATED_PLAYERS_RESPONSE: 1010,
};
Object.defineProperty(MessageId, "__descriptor", {
    value: {
        name: "MessageId",
        get clrType() { return MessageId; },
        fullName: "pokeworld.user.cs.MessageId",
        package: "pokeworld.user.cs",
        values: [
            {name: "INVALID", originalName: "MESSAGE_ID_INVALID", number: 0},
            {name: "REGISTER_REQUEST", originalName: "MESSAGE_ID_REGISTER_REQUEST", number: 1001},
            {name: "REGISTER_RESPONSE", originalName: "MESSAGE_ID_REGISTER_RESPONSE", number: 1002},
            {name: "LOGIN_REQUEST", originalName: "MESSAGE_ID_LOGIN_REQUEST", number: 1003},
            {name: "LOGIN_RESPONSE", originalName: "MESSAGE_ID_LOGIN_RESPONSE", number: 1004},
            {name: "ENTER_SERVER_REQUEST", originalName: "MESSAGE_ID_ENTER_SERVER_REQUEST", number: 1005},
            {name: "ENTER_SERVER_RESPONSE", originalName: "MESSAGE_ID_ENTER_SERVER_RESPONSE", number: 1006},
            {name: "GET_SERVERS_REQUEST", originalName: "MESSAGE_ID_GET_SERVERS_REQUEST", number: 1007},
            {name: "GET_SERVERS_RESPONSE", originalName: "MESSAGE_ID_GET_SERVERS_RESPONSE", number: 1008},
            {name: "GET_CREATED_PLAYERS_REQUEST", originalName: "MESSAGE_ID_GET_CREATED_PLAYERS_REQUEST", number: 1009},
            {name: "GET_CREATED_PLAYERS_RESPONSE", originalName: "MESSAGE_ID_GET_CREATED_PLAYERS_RESPONSE", number: 1010}
        ]
    },
    enumerable: false,
    writable: false,
});
Object.freeze(MessageId);

// Message: RegisterRequest
export class RegisterRequest {
    static __descriptor = {
        name: "RegisterRequest",
        get clrType() { return RegisterRequest; },
        fullName: "pokeworld.user.cs.RegisterRequest",
        package: "pokeworld.user.cs",
        fields: [
            {name: "email", number: 1, type: "TYPE_STRING", label: "LABEL_OPTIONAL"},
            {name: "userName", number: 2, type: "TYPE_STRING", label: "LABEL_OPTIONAL"},
            {name: "password", number: 3, type: "TYPE_STRING", label: "LABEL_OPTIONAL"}
        ]
    }

    /** @type {string} */
    email;

    /** 
     * @param {string} value 
     * @return {RegisterRequest} 
     */
    withEmail(value) {
        this.email = value;
        return this;
    }

    /** @type {string} */
    userName;

    /** 
     * @param {string} value 
     * @return {RegisterRequest} 
     */
    withUserName(value) {
        this.userName = value;
        return this;
    }

    /** @type {string} */
    password;

    /** 
     * @param {string} value 
     * @return {RegisterRequest} 
     */
    withPassword(value) {
        this.password = value;
        return this;
    }

}

// Message: RegisterResponse
export class RegisterResponse {
    static __descriptor = {
        name: "RegisterResponse",
        get clrType() { return RegisterResponse; },
        fullName: "pokeworld.user.cs.RegisterResponse",
        package: "pokeworld.user.cs",
        fields: [
            {name: "success", number: 1, type: "TYPE_BOOL", label: "LABEL_OPTIONAL"}
        ]
    }

    /** @type {boolean} */
    success;

    /** 
     * @param {boolean} value 
     * @return {RegisterResponse} 
     */
    withSuccess(value) {
        this.success = value;
        return this;
    }

}

// Message: LoginRequest
export class LoginRequest {
    static __descriptor = {
        name: "LoginRequest",
        get clrType() { return LoginRequest; },
        fullName: "pokeworld.user.cs.LoginRequest",
        package: "pokeworld.user.cs",
        fields: [
            {name: "email", number: 1, type: "TYPE_STRING", label: "LABEL_OPTIONAL"},
            {name: "password", number: 2, type: "TYPE_STRING", label: "LABEL_OPTIONAL"}
        ]
    }

    /** @type {string} */
    email;

    /** 
     * @param {string} value 
     * @return {LoginRequest} 
     */
    withEmail(value) {
        this.email = value;
        return this;
    }

    /** @type {string} */
    password;

    /** 
     * @param {string} value 
     * @return {LoginRequest} 
     */
    withPassword(value) {
        this.password = value;
        return this;
    }

}

// Message: LoginResponse
export class LoginResponse {
    static __descriptor = {
        name: "LoginResponse",
        get clrType() { return LoginResponse; },
        fullName: "pokeworld.user.cs.LoginResponse",
        package: "pokeworld.user.cs",
        fields: [
            {name: "success", number: 1, type: "TYPE_BOOL", label: "LABEL_OPTIONAL"}
        ]
    }

    /** @type {boolean} */
    success;

    /** 
     * @param {boolean} value 
     * @return {LoginResponse} 
     */
    withSuccess(value) {
        this.success = value;
        return this;
    }

}

// Message: EnterServerRequest
export class EnterServerRequest {
    static __descriptor = {
        name: "EnterServerRequest",
        get clrType() { return EnterServerRequest; },
        fullName: "pokeworld.user.cs.EnterServerRequest",
        package: "pokeworld.user.cs",
        fields: [
            {name: "serverId", number: 1, type: "TYPE_INT32", label: "LABEL_OPTIONAL"}
        ]
    }

    /** @type {number} */
    serverId;

    /** 
     * @param {number} value 
     * @return {EnterServerRequest} 
     */
    withServerId(value) {
        this.serverId = value;
        return this;
    }

}

// Message: EnterServerResponse
export class EnterServerResponse {
    static __descriptor = {
        name: "EnterServerResponse",
        get clrType() { return EnterServerResponse; },
        fullName: "pokeworld.user.cs.EnterServerResponse",
        package: "pokeworld.user.cs",
        fields: [
            {name: "success", number: 1, type: "TYPE_BOOL", label: "LABEL_OPTIONAL"}
        ]
    }

    /** @type {boolean} */
    success;

    /** 
     * @param {boolean} value 
     * @return {EnterServerResponse} 
     */
    withSuccess(value) {
        this.success = value;
        return this;
    }

}

// Message: GetServersRequest
export class GetServersRequest {
    static __descriptor = {
        name: "GetServersRequest",
        get clrType() { return GetServersRequest; },
        fullName: "pokeworld.user.cs.GetServersRequest",
        package: "pokeworld.user.cs",
        fields: []
    }

}

// Message: Server
export class Server {
    static __descriptor = {
        name: "Server",
        get clrType() { return Server; },
        fullName: "pokeworld.user.cs.Server",
        package: "pokeworld.user.cs",
        fields: [
            {name: "id", number: 1, type: "TYPE_INT32", label: "LABEL_OPTIONAL"},
            {name: "name", number: 2, type: "TYPE_STRING", label: "LABEL_OPTIONAL"},
            {name: "number", number: 3, type: "TYPE_UINT32", label: "LABEL_OPTIONAL"}
        ]
    }

    /** @type {number} */
    id;

    /** 
     * @param {number} value 
     * @return {Server} 
     */
    withId(value) {
        this.id = value;
        return this;
    }

    /** @type {string} */
    name;

    /** 
     * @param {string} value 
     * @return {Server} 
     */
    withName(value) {
        this.name = value;
        return this;
    }

    /** @type {number} */
    number;

    /** 
     * @param {number} value 
     * @return {Server} 
     */
    withNumber(value) {
        this.number = value;
        return this;
    }

}

// Message: GetServersResponse
export class GetServersResponse {
    static __descriptor = {
        name: "GetServersResponse",
        get clrType() { return GetServersResponse; },
        fullName: "pokeworld.user.cs.GetServersResponse",
        package: "pokeworld.user.cs",
        fields: [
            {name: "success", number: 1, type: "TYPE_BOOL", label: "LABEL_OPTIONAL"},
            {name: "servers", number: 2, type: "TYPE_MESSAGE", typeName: ".pokeworld.user.cs.Server", get clrType() { return Server; }, label: "LABEL_REPEATED"}
        ]
    }

    /** @type {boolean} */
    success;

    /** 
     * @param {boolean} value 
     * @return {GetServersResponse} 
     */
    withSuccess(value) {
        this.success = value;
        return this;
    }

    /** @type {Server[]} */
    servers;

    /** 
     * @param {Server[]} value 
     * @return {GetServersResponse} 
     */
    withServers(value) {
        this.servers = value;
        return this;
    }

}

// Message: GetCreatedPlayersRequest
export class GetCreatedPlayersRequest {
    static __descriptor = {
        name: "GetCreatedPlayersRequest",
        get clrType() { return GetCreatedPlayersRequest; },
        fullName: "pokeworld.user.cs.GetCreatedPlayersRequest",
        package: "pokeworld.user.cs",
        fields: []
    }

}

// Message: GetCreatedPlayersResponse
export class GetCreatedPlayersResponse {
    static __descriptor = {
        name: "GetCreatedPlayersResponse",
        get clrType() { return GetCreatedPlayersResponse; },
        fullName: "pokeworld.user.cs.GetCreatedPlayersResponse",
        package: "pokeworld.user.cs",
        fields: [
            {name: "success", number: 1, type: "TYPE_BOOL", label: "LABEL_OPTIONAL"},
            {name: "entityIds", number: 2, type: "TYPE_UINT64", label: "LABEL_REPEATED"}
        ]
    }

    /** @type {boolean} */
    success;

    /** 
     * @param {boolean} value 
     * @return {GetCreatedPlayersResponse} 
     */
    withSuccess(value) {
        this.success = value;
        return this;
    }

    /** @type {number[]} */
    entityIds;

    /** 
     * @param {number[]} value 
     * @return {GetCreatedPlayersResponse} 
     */
    withEntityIds(value) {
        this.entityIds = value;
        return this;
    }

}

