// Auto-generated by multjs C++ transpiler
#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <variant>

#include "mjs/cpp_gen/mjs_runtime.h"

namespace pokemon_game {

auto calculateDamage(auto base, auto multiplier, auto critical) {
    auto damage = (base * multiplier);
    if (critical) {
        damage = (damage * 2);
    }
    return damage;
}


    void initialize() {
        auto player = JSObject({{"name", "Ash"}, {"level", 25}, {"health", 100}});
        int64_t attackPower = 50;
        int64_t defense = 20;
        bool isCritical = true;
        auto finalDamage = calculateDamage(attackPower, 1.5, isCritical);
        auto remainingHealth = (player.health - finalDamage);
        std::vector<std::string> items = {"Potion", "Antidote", "Paralyze Heal"};
        for (int64_t i = 0; (i < items.size()); /* unsupported expression */) {
            auto itemName = items[i];
        }
        if ((remainingHealth <= 0)) {
            player.health = 0;
        }
        else {
            player.health = remainingHealth;
        }
    }

} // namespace pokemon_game
